import './globals.css'
import { Climate_Crisis } from "next/font/google"
import Script from "next/script"

const cc = Climate_Crisis({subsets: ['latin']})

export const metadata = {
  title: 'Tournament Organizer & Scorekeeper',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={cc.className}>{children}</body>
      <Script src="https://kit.fontawesome.com/fa314c8795.js" crossOrigin="anonymous"/>
    </html>
  )
}
